# Generated by Django 4.2.1 on 2023-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productdetailt_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pictureUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logoUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
