# Generated by Django 4.2.1 on 2023-05-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_pictureurl_store_logourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logoUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
