# Generated by Django 4.2.1 on 2023-05-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_logourl_category_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
